### PR TITLE
Migration from SOSS to Integration Service

### PR DESCRIPTION
**Pull request by jamoralp**
This pull request is going to be used to check that changes made in `feature/soss-core-to-is-core` branch are working properly.

When the tests here success, merge https://github.com/eProsima/soss/pull/57.

This pull request can then be closed, but the branch **[[[SHOULD NOT BE DELETED]]]**. The work done in this branch will serve as a starting point for separating all the packages into dedicated repositories containing the Integration Service SystemHandle plugins for the ROS 2 and Websocket libraries.

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/151/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/153/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/154/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/155/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/157/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/158/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/159/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/180/)

**Comment by jamoralp** [comment]
Closing since already passed

**Pull request closed without merging**
