### PR TITLE
Change ros2-test and websocket-test to use GTest instead of Catch

### PR DESCRIPTION
**Pull request by lauramg15**

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/145/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/150/)

**Review by jamoralp — APPROVED** [review]
:+1:

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/162/)

**Pull request merged**
